# Generated by Django 4.1 on 2023-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbooks',
            name='rel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
