# Generated by Django 4.1 on 2023-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_studentbooks_rel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=200)),
                ('lastname', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
